### ISSUE TITLE
Is it possible to show the path of the circle movement?

### ISSUE THREAD

**Issue by AK51** [alex-controlx/red-dashboard-svg-control#10]
Hi, I can follow the instruction and make a circle to move around. 
And I want to show the path of the circle movement, but I could not think of a way....
Is it possible to show the path of the movement?
I am thinking if drawing lines is possible....

Thx

**Comment by alex-controlx** [comment]
Drawing a line dynamically would be a great feature, however it isn't possible in current version.
As an option you can pre-draw the lines use cx_hide APIs to hide and show them. I guess it would work if the circle has predefined trajectory.

**Comment by AK51** [comment]
Thx, instead, I have created several circles to indicate the history of the location. Cheers.
