### ISSUE TITLE
Is there a way to have the Pivot point parameters to be absolute and not relative to the container?

### ISSUE THREAD

**Issue by thelwyn** [alex-controlx/red-dashboard-svg-control#11]
Sorry, I know it's simply not made to work this way, but I would need to be able to rotate related to a fixed pivot point and not have it moved everytime I translate the object first.

Do you think of a way around that issue than I'm not thinking of?

Thank you!

**Comment by alex-controlx** [comment]
if you trying to send something like this `{"payload":{"x":0,"y":0,"deg":17},"topic":"T-101_level@cx_move"}` and it doesn't rotate then the problem with the SVG file.

However, I suppose you are sending a message like above and it jumps somewhere else, is it correct?

**Comment by thelwyn** [comment]
It works as intended, that is if, I do a rotation, it will rotate around the pivot point defined relatively to its container. 

My first message was unclear and actually my "problem" even bigger, because the way the pivot point is defined "locally" it means it can't be a point "outside" of its container somewhere else in a bigger canvas, is that right?

Let say my canvas is 400x400 , I try to rotate a rectangle that is 50x50 and centered on this canvas, but my pivot is top left corner of the canvas: I can't rotate this way, because the pivot point can only be in the 50x50 area of the rectangle?

Sorry I'm very new to SVG AND Nodered, I might be using the wrong words and confusing you even more =)

**Comment by alex-controlx** [comment]
Not confusing it's me. The first time I read your comment without reading the question. Sorry for making you to explain it again.

Answering your question: Currently it doesn't support absolute coordinates for the pivot parameter. However it is a great feature for v2 of the framework.

As a workaround you can try creating a canvas size transparent rectangle with your 50x50 rectangle inside. Then rotate the parent rectangle. 

Hope it helps.

**Comment by thelwyn** [comment]
@alex-controlx thank you for taking the time to answer :)
